import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../(main)/globals.css';
import { Toaster } from '@/components/ui/toaster';
import StoreProvider from '../(main)/StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Human Hub',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          {children}
          <Toaster />
        </body>
      </html>
    </StoreProvider>
  );
}
