// app/layout.tsx
import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import StoreProvider from './StoreProvider';
import './globals.css';
import ClientLayout from '@/components/custom/ClientLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Human Hub',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <StoreProvider>
        <html lang="en">
          <body className={inter.className}>
            <ClientLayout>{children}</ClientLayout>
          </body>
        </html>
      </StoreProvider>
    
  );
}
