// app/layout.tsx
import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import StoreProvider from '@/components/custom/StoreProvider';
import './globals.css';
import ClientLayout from '@/components/custom/ClientLayout';
import { Toaster } from '@/components/ui/toaster';
import { ThemeProvider } from '@/components/custom/Theme/ThemeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Human Hub',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ClientLayout>
              {children}
              <Toaster />
            </ClientLayout>
          </ThemeProvider>
        </body>
      </html>
    </StoreProvider>
  );
}
